/**
 * Home page copy and main markup (ES / EN / FR / PT).
 * Edit here, then: npm run build:home
 * Refresh from HTML: node scripts/extract-home-content.mjs
 */
import { LANG_CODES } from "./languages.mjs";
import { sitePath } from "./i18n-urls.mjs";
import { escAttr, escHtml } from "./html-utils.mjs";
import {
  googleReviewWriteUrl,
  googleReviewsListUrl,
} from "./google-place.mjs";
import { SITE_OG_IMAGE } from "./page-shell.mjs";
import { waMeUrl } from "./site-contact.mjs";

export const HOME_OG_IMAGE = SITE_OG_IMAGE;
/** @deprecated Use HOME_OG_IMAGE for social previews. */
export const HOME_HERO_IMAGE = HOME_OG_IMAGE;

const HOME_WHATSAPP_HREF = waMeUrl();

/** Kinesica + estación Scalabrini Ortiz (D) visibles al cargar. Regenerar: Maps → encuadrar → Compartir → Insertar mapa. */
const MAP_EMBED_BASE =
  "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5720.6828547033!2d-58.421280!3d-34.586220!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcb5d25b8f6967%3A0xb83b91819649edc!2sKinesica!5e0!3m2!1";

/** @param {import("./languages.mjs").LangCode} lang */
export function mapEmbedSrc(lang) {
  const hl = lang === "es" ? "ses" : lang;
  return `${MAP_EMBED_BASE}${hl}!2${hl}!4v1742940067621!5m2!1${hl}!2${hl}`;
}

const MAP_EMBED_TITLES = {
  es: "Ubicación de Kinésica en Google Maps",
  en: "Kinésica location on Google Maps",
  fr: "Localisation de Kinésica sur Google Maps",
  pt: "Localização da Kinésica no Google Maps",
};

/** @param {import("./languages.mjs").LangCode} lang */
export function mapEmbedFrameBlock(lang) {
  const title = MAP_EMBED_TITLES[lang] || MAP_EMBED_TITLES.es;
  const src = mapEmbedSrc(lang);
  return [
    "                <div class=\"map-embed-frame\">",
    `              <div class="map-embed-facade" data-embed-src="${src}" data-embed-title="${title}" aria-label="${title}" aria-busy="true"></div>`,
    "                </div>",
  ];
}

const MAP_REVIEWS_COPY = {
  es: {
    moreReviewsLabel: "Ver todas nuestras valoraciones en Google",
    moreReviewsTitle: "Ver todas nuestras valoraciones en Google",
  },
  en: {
    moreReviewsLabel: "See all our Google reviews",
    moreReviewsTitle: "See all our Google reviews",
  },
  fr: {
    moreReviewsLabel: "Voir toutes nos évaluations sur Google",
    moreReviewsTitle: "Voir toutes nos évaluations sur Google",
  },
  pt: {
    moreReviewsLabel: "Ver todas as nossas avaliações no Google",
    moreReviewsTitle: "Ver todas as nossas avaliações no Google",
  },
};

const TEAM_ABOUT = {
  es: {
    eyebrow: "Sobre nosotros",
    title: "Profesionales dedicados a tu bienestar",
    lead:
      "Somos kinesiólogos en constante formación, dedicados a la <span class=\"text-highlight\">Terapia Manual</span> para abordar a cada paciente de forma integral. Buscamos el tratamiento específico que necesitás para dejar de vivir con dolor.",
    members: [
      {
        name: "Norberto Brude",
        title: "Lic. Kinesiólogo Fisiatra",
        img: "noberto-brude-kinesiologo-osteopata.webp",
        imgTitle: "Norberto Brude Kinesiólogo Osteópata",
        imgAlt: "Norberto Brude Kinesiologo Osteopata",
        cvLabel: "Currículum",
        cvHref: "cv.html",
      },
      {
        name: "María Gulín",
        title: "Lic. Kinesióloga Fisiatra",
        img: "maria.webp",
        imgTitle: "María Gulín Kinesióloga Fisiatra",
        imgAlt: "María Gulín Kinesióloga Fisiatra",
      },
    ],
  },
  en: {
    eyebrow: "About us",
    title: "Professionals dedicated to your wellbeing",
    lead:
      "We are kinesiologists in ongoing training, dedicated to <span class=\"text-highlight\">Manual Therapy</span> for a whole-person approach. We look for the specific treatment you need so you can stop living with pain.",
    members: [
      {
        name: "Norberto Brude",
        title: "Licensed Kinesiologist & Physiatrist",
        img: "noberto-brude-kinesiologo-osteopata.webp",
        imgTitle: "Norberto Brude Physiotherapist Osteopath",
        imgAlt: "Norberto Brude Physiotherapist Osteopath",
        cvLabel: "Résumé",
        cvHref: "cv.html",
      },
      {
        name: "María Gulín",
        title: "Licensed Kinesiologist & Physiatrist",
        img: "maria.webp",
        imgTitle: "María Gulín Licensed Kinesiologist & Physiatrist",
        imgAlt: "María Gulín Licensed Kinesiologist & Physiatrist",
      },
    ],
  },
  fr: {
    eyebrow: "À propos",
    title: "Des praticiens dédiés à votre bien-être",
    lead:
      "Nous sommes kinésithérapeutes en formation continue, dédiés à la <span class=\"text-highlight\">thérapie manuelle</span> pour une prise en charge globale. Nous cherchons le traitement adapté pour que vous cessiez de vivre avec la douleur.",
    members: [
      {
        name: "Norberto Brude",
        title: "Kinésithérapeute et physiatre",
        img: "noberto-brude-kinesiologo-osteopata.webp",
        imgTitle: "Norberto Brude — kinésithérapeute ostéopathe",
        imgAlt: "Norberto Brude — kinésithérapeute ostéopathe",
        cvLabel: "CV",
        cvHref: "cv.html",
      },
      {
        name: "María Gulín",
        title: "Kinésithérapeute et physiatre",
        img: "maria.webp",
        imgTitle: "María Gulín — kinésithérapeute et physiatre",
        imgAlt: "María Gulín — kinésithérapeute et physiatre",
      },
    ],
  },
  pt: {
    eyebrow: "Sobre nós",
    title: "Profissionais dedicados ao seu bem-estar",
    lead:
      "Somos fisioterapeutas em formação contínua, dedicados à <span class=\"text-highlight\">terapia manual</span> para um cuidado integral. Buscamos o tratamento específico para você deixar de viver com dor.",
    members: [
      {
        name: "Norberto Brude",
        title: "Licenciado em fisioterapia e fisiatria",
        img: "noberto-brude-kinesiologo-osteopata.webp",
        imgTitle: "Norberto Brude — fisioterapeuta e osteopata",
        imgAlt: "Norberto Brude — fisioterapeuta e osteopata",
        cvLabel: "Currículo",
        cvHref: "cv.html",
      },
      {
        name: "María Gulín",
        title: "Licenciada em fisioterapia e fisiatria",
        img: "maria.webp",
        imgTitle: "María Gulín — fisioterapeuta e fisiatra",
        imgAlt: "María Gulín — fisioterapeuta e fisiatra",
      },
    ],
  },
};

/** Home method cards (order and copy as published). Not all METHOD_STEMS. */
export const HOME_METHOD_CARD_STEMS = [
  "rpg",
  "osteopatia",
  "cadenas",
  "manipulaciones",
  "neurodinamia",
  "atm",
];

const HOME_METHOD_CARD_IMAGES = {
  rpg: "rpg.webp",
  osteopatia: "osteopatia.webp",
  cadenas: "cadenas_fisiologicas.webp",
  manipulaciones: "manipulaciones_viscerales.webp",
  neurodinamia: "neurodinamia.webp",
  atm: "atm.webp",
};

/** Visible card copy — keep in sync with current home UI. */
const HOME_METHOD_CARDS = {
  rpg: {
    es: {
      title: "RPG",
      imgTitle: "rpg",
      imgAlt: "Sesión de Reeducación Postural Global (RPG)",
      lead: "Flexibilización de los músculos estáticos.",
    },
    en: {
      title: "RPG",
      imgTitle: "RPG",
      imgAlt: "Global Postural Reeducation (RPG) session",
      lead: "Flexibility work on static muscles.",
    },
    fr: {
      title: "RPG",
      imgTitle: "RPG",
      imgAlt: "Séance de rééducation posturale globale (RPG)",
      lead: "Assouplissement des muscles statiques.",
    },
    pt: {
      title: "RPG",
      imgTitle: "RPG",
      imgAlt: "Sessão de Reeducação Postural Global (RPG)",
      lead: "Flexibilização dos músculos estáticos.",
    },
  },
  osteopatia: {
    es: {
      title: "Osteopatía",
      imgTitle: "osteopatía",
      imgAlt: "Tratamiento de Osteopatía manual",
      lead: "Movilidad de los tejidos para restablecer la salud.",
    },
    en: {
      title: "Osteopathy",
      imgTitle: "Osteopathy",
      imgAlt: "Manual Osteopathy treatment",
      lead: "Tissue mobility to restore health.",
    },
    fr: {
      title: "Ostéopathie",
      imgTitle: "Ostéopathie",
      imgAlt: "Traitement d'ostéopathie manuelle",
      lead: "Mobilité des tissus pour rétablir la santé.",
    },
    pt: {
      title: "Osteopatia",
      imgTitle: "Osteopatia",
      imgAlt: "Tratamento de osteopatia manual",
      lead: "Mobilidade dos tecidos para restabelecer a saúde.",
    },
  },
  cadenas: {
    es: {
      title: "Cadenas Fisiológicas",
      imgTitle: "Cadenas Fisiológicas",
      imgAlt: "Tratamiento de Cadenas Fisiológicas",
      lead: "Estructura y vísceras en la estática y el movimiento.",
    },
    en: {
      title: "Physiological Chains",
      imgTitle: "Physiological Chains",
      imgAlt: "Physiological Chains treatment",
      lead: "Body structure and viscera in stance and movement.",
    },
    fr: {
      title: "Chaînes physiologiques",
      imgTitle: "Chaînes physiologiques",
      imgAlt: "Traitement des chaînes physiologiques",
      lead: "Structure et viscères, en statique et en mouvement.",
    },
    pt: {
      title: "Cadeias fisiológicas",
      imgTitle: "Cadeias fisiológicas",
      imgAlt: "Tratamento de cadeias fisiológicas",
      lead: "Estrutura e vísceras na estática e no movimento.",
    },
  },
  manipulaciones: {
    es: {
      title: "Manipulaciones viscerales",
      imgTitle: "Manipulaciones Viscerales",
      imgAlt: "Terapia de manipulaciones viscerales",
      lead: "Tensiones viscerales que condicionan el aparato locomotor.",
    },
    en: {
      title: "Visceral Manipulations",
      imgTitle: "Visceral manipulations",
      imgAlt: "Visceral manipulations therapy",
      lead: "Visceral tension that conditions the locomotor system.",
    },
    fr: {
      title: "Manipulations viscérales",
      imgTitle: "Manipulations viscérales",
      imgAlt: "Thérapie par manipulations viscérales",
      lead: "Tensions viscérales qui conditionnent l'appareil locomoteur.",
    },
    pt: {
      title: "Manipulações viscerais",
      imgTitle: "Manipulações viscerais",
      imgAlt: "Terapia por manipulações viscerais",
      lead: "Tensões viscerais que condicionam o aparelho locomotor.",
    },
  },
  neurodinamia: {
    es: {
      title: "Neurodinamia",
      imgTitle: "Neurodinamia",
      imgAlt: "Tratamiento de Neurodinamia",
      lead: "Deslizamiento nervioso para aliviar el dolor.",
    },
    en: {
      title: "Neurodynamics",
      imgTitle: "Neurodynamics",
      imgAlt: "Neurodynamics treatment",
      lead: "Nerve gliding to relieve pain.",
    },
    fr: {
      title: "Neurodynamique",
      imgTitle: "Neurodynamique",
      imgAlt: "Traitement neurodynamique",
      lead: "Glissement nerveux pour soulager la douleur.",
    },
    pt: {
      title: "Neurodinâmica",
      imgTitle: "Neurodinâmica",
      imgAlt: "Tratamento de neurodinâmica",
      lead: "Deslizamento nervoso para aliviar a dor.",
    },
  },
  atm: {
    es: {
      title: "ATM",
      imgTitle: "ATM",
      imgAlt: "Tratamiento de ATM – articulación temporomandibular",
      lead: "Tratamiento de bruxismo y disfunción de ATM.",
    },
    en: {
      title: "TMJ",
      imgTitle: "TMJ",
      imgAlt: "TMJ temporomandibular joint treatment",
      lead: "Treatment for bruxism and TMJ dysfunction.",
    },
    fr: {
      title: "ATM",
      imgTitle: "ATM",
      imgAlt: "Traitement de l'ATM (articulation temporomandibulaire)",
      lead: "Traitement du bruxisme et des troubles de l'ATM.",
    },
    pt: {
      title: "ATM",
      imgTitle: "ATM",
      imgAlt: "Tratamento de ATM (articulação temporomandibular)",
      lead: "Tratamento de bruxismo e disfunção da ATM.",
    },
  },
};

function homeMethodCard(lang, stem) {
  const href = sitePath(lang, stem);
  const image = HOME_METHOD_CARD_IMAGES[stem];
  const card = HOME_METHOD_CARDS[stem][lang];
  return [
    "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
    "            <div class=\"service-block\">",
    "              <div class=\"service-img mb20\">",
    `                <a href="${escAttr(href)}"><img src="__PREFIX__images/${image}" title="${escAttr(card.imgTitle)}"`,
    `                    alt="${escAttr(card.imgAlt)}" class="img-responsive" loading="lazy" /></a>`,
    "              </div>",
    "              <div class=\"service-content\">",
    `                <h2><a href="${escAttr(href)}" class="title">${escHtml(card.title)}</a></h2>`,
    `                <p>${escHtml(card.lead)}</p>`,
    "              </div>",
    "            </div>",
    "          </div>",
  ];
}

/** Two rows of three method cards; hrefs via sitePath(lang, stem). */
export function renderHomeMethodCards(lang) {
  const row1 = HOME_METHOD_CARD_STEMS.slice(0, 3);
  const row2 = HOME_METHOD_CARD_STEMS.slice(3);
  return [
    "        <div class=\"row\">",
    ...row1.flatMap((stem) => homeMethodCard(lang, stem)),
    "        </div>",
    "        <br />",
    "        <div class=\"row\">",
    ...row2.flatMap((stem) => homeMethodCard(lang, stem)),
    "        </div>",
  ];
}

/** @param {import("./languages.mjs").LangCode} lang */
function teamAboutSection(lang) {
  const copy = TEAM_ABOUT[lang] || TEAM_ABOUT.es;
  const memberBlocks = copy.members.flatMap((member) => {
    const cvMeta = member.cvHref
      ? [
          "                <div class=\"team-meta\">",
          "                  <span class=\"team-designation\">",
          `                    <a href=\"${member.cvHref}\">${member.cvLabel}</a>`,
          "                  </span>",
          "                </div>",
        ]
      : [];
    return [
      "              <div class=\"team-block\">",
      "                <div class=\"team-img\">",
      `                  <img src=\"__PREFIX__images/${member.img}\" title=\"${member.imgTitle}\"`,
      `                    alt=\"${member.imgAlt}\" class=\"team-photo center-block d-block\" width=\"314\"`,
      "                    height=\"372\" loading=\"lazy\" />",
      "                </div>",
      "                <div class=\"team-content\">",
      `                  <h2 class=\"team-title\">${member.name}</h2>`,
      "                  <div class=\"team-meta\">",
      `                    <span class=\"team-designation\">${member.title}</span>`,
      "                  </div>",
      ...cvMeta,
      "                </div>",
      "              </div>",
    ];
  });

  return [
    "<section class=\"space-medium section-intro section-intro--about\">",
    "      <div class=\"container\">",
    "        <div class=\"row\">",
    "          <div class=\"col-lg-offset-1 col-lg-10 col-md-offset-1 col-md-10 col-sm-12 col-xs-12\">",
    "            <div class=\"section-title mb60 text-center\">",
    "              <!-- section title start-->",
    `              <p class=\"section-eyebrow\">${copy.eyebrow}</p>`,
    `              <h2 class=\"heading-line-center\">${copy.title}</h2>`,
    "              <p class=\"section-lead\">",
    `                ${copy.lead}`,
    "              </p>",
    "            </div>",
    "            <!-- /.section title end-->",
    "          </div>",
    "        </div>",
    "        <div class=\"row\">",
    "          <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">",
    "            <div class=\"team-grid\">",
    ...memberBlocks,
    "            </div>",
    "          </div>",
    "        </div>",
    "      </div>",
    "    </section>",
  ];
}

/** Google review cards (Places API → npm run reviews:fetch or js/google-reviews.js). */
export function googleReviewsBlock(lang) {
  const copy = MAP_REVIEWS_COPY[lang] || MAP_REVIEWS_COPY.es;
  const listUrl = googleReviewsListUrl();
  return [
    "            <div class=\"map-reviews-aside\" hidden>",
    "              <div class=\"google-reviews-wrap\">",
    `              <section id="google-reviews-section" class="google-reviews" data-reviews-lang="${lang}" hidden>`,
    "                <div id=\"google-reviews-grid\" class=\"google-reviews-grid\"></div>",
    "              </section>",
    "              <script src=\"__PREFIX__js/reviews.min.js\" defer></script>",
    "              </div>",
    "              <p class=\"google-reviews-more\">",
    `                <a href="${listUrl}" class="google-reviews-more-link" target="_blank" rel="noopener noreferrer" title="${copy.moreReviewsTitle}">${copy.moreReviewsLabel} <i class="fa fa-arrow-right" aria-hidden="true"></i></a>`,
    "              </p>",
    "            </div>",
  ];
}

/** @type {Record<import("./languages.mjs").LangCode, HomeLang>} */
export const HOME = {
  es: {
    title: "Kinésica - Kinesiología, Osteopatía, RPG y ATM",
    description: "Kinésica es un centro de kinesiología, osteopatía, RPG y ATM en Palermo. Terapias manuales personalizadas.",
    ogDescription: "Kinésica es un centro de kinesiología, osteopatía, RPG y ATM en Palermo. Terapias manuales personalizadas.",
    twitterDescription: "Kinésica es un centro de kinesiología, osteopatía, RPG y ATM en Palermo. Terapias manuales personalizadas.",
    twitterImageAlt: "Centro Kinésica — kinesiología, osteopatía, RPG y ATM en Palermo",
    mainHtml: [
      "<section class=\"hero-section\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-5\">",
      "            <h1 class=\"hero-title\">Kinesiología <br />RPG <br />Osteopatía <br />ATM</h1>",
      "            <p class=\"hero-text\">",
      "              No te acostumbres a vivir con dolor, podemos encontrar juntos un",
      "              camino para que vivas mejor.",
      "            </p>",
      `            <a href="${HOME_WHATSAPP_HREF}" target="_blank" class="btn btn-default dynamic-whatsapp-url"`,
      "              rel=\"noopener noreferrer\">Contacto y turnos</a>",
      "</div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    <section class=\"space-medium section-intro section-intro--band\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-offset-2 col-md-8\">",
      "            <div class=\"mb60 text-center section-title\">",
      "              <!-- section title start-->",
      "              <p class=\"section-eyebrow\">Terapias</p>",
      "              <h2 class=\"heading-line-center\">Métodos y Técnicas</h2>",
      "              <p class=\"section-lead\">",
      "                Trabajamos en <span class=\"text-highlight\">Terapia Manual</span>.",
      "                Los diferentes métodos nos permiten abordar al paciente desde",
      "                distintos puntos de vista.",
      "              </p>",
      "            </div>",
      "            <!-- /.section title start-->",
      "          </div>",
      "        </div>",
      ...renderHomeMethodCards("es"),
      "      </div>",
      "    </section>",
      "    __CTA_PLACEHOLDER__",
      ...teamAboutSection("es"),
      "    <section class=\"space-small bg-default section-intro section-intro--compact\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">",
      "            <div class=\"section-title mb40 text-center\">",
      "              <p class=\"section-eyebrow\">Ubicación</p>",
      "              <h2 class=\"heading-line-center\">¿Dónde estamos?</h2>",
      "            </div>",
      "          </div>",
      "        </div>",
      "        <div class=\"map-block\">",
      "          <div class=\"map-reviews-panel\">",
      "            <div class=\"map-reviews-grid\">",
      "              <div class=\"map-reviews-map\">",
      ...mapEmbedFrameBlock("es"),
      "                <div class=\"map-transit-wrap\">",
      "                <div class=\"map-transit-panel\">",
      "                  <div class=\"map-transit-grid\">",
      "                    <article class=\"map-transit-card map-transit-card--subte\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-train\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Subte</h3>",
      "                        <p class=\"map-transit-card-detail\">",
      "                          <span class=\"map-transit-badge map-transit-badge--line-d\">D</span>",
      "                          Scalabrini Ortiz",
      "                        </p>",
      "                      </div>",
      "                    </article>",
      "                    <article class=\"map-transit-card map-transit-card--bus\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Colectivos</h3>",
      "                        <ul class=\"map-transit-lines\" aria-label=\"Líneas de colectivo\">",
      "                          <li>39</li>",
      "                          <li>64</li>",
      "                          <li>68</li>",
      "                          <li>111</li>",
      "                          <li>152</li>",
      "                          <li>160</li>",
      "                        </ul>",
      "                      </div>",
      "                    </article>",
      "                  </div>",
      "                </div>",
      "              </div>",
      "            </div>",
      "__GOOGLE_REVIEWS_PLACEHOLDER__",
      "            </div>",
      "          </div>",
      "          <aside id=\"map-review-cta\" class=\"map-review-cta\" aria-label=\"Reseñas en Google\">",
      "            <div class=\"map-review-cta-inner\">",
      "              <span class=\"map-review-cta-icon\" aria-hidden=\"true\"><i class=\"fa fa-star\"></i></span>",
      "              <div class=\"map-review-cta-body\">",
      "                <p class=\"map-review-cta-text\">",
      "                  ¿Te ha ido bien con nosotros?<br>",
      `                  <a href="${googleReviewWriteUrl()}" class="map-review-cta-link" target="_blank" rel="noopener noreferrer" title="Dejar una reseña en Google">¡Ayúdanos con una reseña!</a>`,
      "                </p>",
      "              </div>",
      "            </div>",
      "          </aside>",
      "        </div>",
      "      </div>",
      "    </section>",
      "__FAQ_ACCORDION__",
    ].join("\n"),
  },
  en: {
    title: "Kinésica - Kinesiology, Osteopathy, RPG and TMJ",
    description: "Kinésica is a clinic for kinesiology, osteopathy, RPG, and TMJ in Palermo offering personalized manual therapy.",
    ogDescription: "Kinésica is a clinic for kinesiology, osteopathy, RPG, and TMJ in Palermo offering personalized manual therapy.",
    twitterDescription: "Kinésica is a clinic for kinesiology, osteopathy, RPG, and TMJ in Palermo offering personalized manual therapy.",
    twitterImageAlt: "Kinésica clinic — kinesiology, osteopathy, RPG and TMJ in Palermo",
    mainHtml: [
      "<section class=\"hero-section\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-5\">",
      "            <h1 class=\"hero-title\">Kinesiology <br />RPG <br />Osteopathy <br />TMJ</h1>",
      "            <p class=\"hero-text\">",
      "              Don't get used to living in pain. Together, we can find a way for",
      "              you to live better.",
      "            </p>",
      `            <a href="${HOME_WHATSAPP_HREF}" target="_blank" class="btn btn-default dynamic-whatsapp-url"`,
      "              rel=\"noopener noreferrer\">Contact & Appointments</a>",
      "</div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    <section class=\"space-medium section-intro section-intro--band\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-offset-2 col-md-8\">",
      "            <div class=\"mb60 text-center section-title\">",
      "              <!-- section title start-->",
      "              <p class=\"section-eyebrow\">Therapies</p>",
      "              <h2 class=\"heading-line-center\">Methods &amp; Techniques</h2>",
      "              <p class=\"section-lead\">",
      "                We work with <span class=\"text-highlight\">Manual Therapy</span>.",
      "                Different methods allow us to approach patients from various",
      "                perspectives.",
      "              </p>",
      "            </div>",
      "            <!-- /.section title start-->",
      "          </div>",
      "        </div>",
      ...renderHomeMethodCards("en"),
      "      </div>",
      "    </section>",
      "          __CTA_PLACEHOLDER__",
      ...teamAboutSection("en"),
      "    <section class=\"space-small bg-default section-intro section-intro--compact\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">",
      "            <div class=\"section-title mb40 text-center\">",
      "              <p class=\"section-eyebrow\">Visit us</p>",
      "              <h2 class=\"heading-line-center\">Location</h2>",
      "            </div>",
      "          </div>",
      "        </div>",
      "        <div class=\"map-block\">",
      "          <div class=\"map-reviews-panel\">",
      "            <div class=\"map-reviews-grid\">",
      "              <div class=\"map-reviews-map\">",
      ...mapEmbedFrameBlock("en"),
      "                <div class=\"map-transit-wrap\">",
      "                <div class=\"map-transit-panel\">",
      "                  <div class=\"map-transit-grid\">",
      "                    <article class=\"map-transit-card map-transit-card--subte\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-train\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Subway</h3>",
      "                        <p class=\"map-transit-card-detail\">",
      "                          <span class=\"map-transit-badge map-transit-badge--line-d\">D</span>",
      "                          Scalabrini Ortiz",
      "                        </p>",
      "                      </div>",
      "                    </article>",
      "                    <article class=\"map-transit-card map-transit-card--bus\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Buses</h3>",
      "                        <ul class=\"map-transit-lines\" aria-label=\"Bus routes\">",
      "                          <li>39</li>",
      "                          <li>64</li>",
      "                          <li>68</li>",
      "                          <li>111</li>",
      "                          <li>152</li>",
      "                          <li>160</li>",
      "                        </ul>",
      "                      </div>",
      "                    </article>",
      "                  </div>",
      "                </div>",
      "              </div>",
      "            </div>",
      "__GOOGLE_REVIEWS_PLACEHOLDER__",
      "            </div>",
      "          </div>",
      "          <aside id=\"map-review-cta\" class=\"map-review-cta\" aria-label=\"Google reviews\">",
      "            <div class=\"map-review-cta-inner\">",
      "              <span class=\"map-review-cta-icon\" aria-hidden=\"true\"><i class=\"fa fa-star\"></i></span>",
      "              <div class=\"map-review-cta-body\">",
      "                <p class=\"map-review-cta-text\">",
      "                  Had a good experience with us?<br>",
      `                  <a href="${googleReviewWriteUrl()}" class="map-review-cta-link" target="_blank" rel="noopener noreferrer" title="Leave a review on Google">Help us with a review!</a>`,
      "                </p>",
      "              </div>",
      "            </div>",
      "          </aside>",
      "        </div>",
      "      </div>",
      "      </section>",
      "__FAQ_ACCORDION__",
    ].join("\n"),
  },
  fr: {
    title: "Kinésica — Kinésithérapie, ostéopathie, RPG et ATM",
    description: "Kinésica est un centre de kinésithérapie, ostéopathie, RPG et ATM à Palermo. Thérapies manuelles personnalisées.",
    ogDescription: "Kinésica est un centre de kinésithérapie, ostéopathie, RPG et ATM à Palermo. Thérapies manuelles personnalisées.",
    twitterDescription: "Kinésica est un centre de kinésithérapie, ostéopathie, RPG et ATM à Palermo. Thérapies manuelles personnalisées.",
    twitterImageAlt: "Centre Kinésica — kinésithérapie, ostéopathie, RPG et ATM à Palermo",
    mainHtml: [
      "<section class=\"hero-section\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-5\">",
      "            <h1 class=\"hero-title\">Kinésithérapie <br />RPG <br />Ostéopathie <br />ATM</h1>",
      "            <p class=\"hero-text\">",
      "              N'habituez pas votre corps à la douleur. Ensemble, nous pouvons trouver une façon de mieux vivre.",
      "            </p>",
      `            <a href="${HOME_WHATSAPP_HREF}" target="_blank" class="btn btn-default dynamic-whatsapp-url"`,
      "              rel=\"noopener noreferrer\">Contact et rendez-vous</a>",
      "</div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    <section class=\"space-medium section-intro section-intro--band\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-offset-2 col-md-8\">",
      "            <div class=\"mb60 text-center section-title\">",
      "              <!-- section title start-->",
      "              <p class=\"section-eyebrow\">Thérapies</p>",
      "              <h2 class=\"heading-line-center\">Méthodes et techniques</h2>",
      "              <p class=\"section-lead\">",
      "                Nous pratiquons la <span class=\"text-highlight\">thérapie manuelle</span>.",
      "                Différentes méthodes nous permettent d'aborder chaque patient sous",
      "                plusieurs angles.",
      "              </p>",
      "            </div>",
      "            <!-- /.section title start-->",
      "          </div>",
      "        </div>",
      ...renderHomeMethodCards("fr"),
      "      </div>",
      "    </section>",
      "          __CTA_PLACEHOLDER__",
      ...teamAboutSection("fr"),
      "    <section class=\"space-small bg-default section-intro section-intro--compact\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">",
      "            <div class=\"section-title mb40 text-center\">",
      "              <p class=\"section-eyebrow\">Adresse</p>",
      "              <h2 class=\"heading-line-center\">Localisation</h2>",
      "            </div>",
      "          </div>",
      "        </div>",
      "        <div class=\"map-block\">",
      "          <div class=\"map-reviews-panel\">",
      "            <div class=\"map-reviews-grid\">",
      "              <div class=\"map-reviews-map\">",
      ...mapEmbedFrameBlock("fr"),
      "                <div class=\"map-transit-wrap\">",
      "                <div class=\"map-transit-panel\">",
      "                  <div class=\"map-transit-grid\">",
      "                    <article class=\"map-transit-card map-transit-card--subte\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-train\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Métro</h3>",
      "                        <p class=\"map-transit-card-detail\">",
      "                          <span class=\"map-transit-badge map-transit-badge--line-d\">D</span>",
      "                          Scalabrini Ortiz",
      "                        </p>",
      "                      </div>",
      "                    </article>",
      "                    <article class=\"map-transit-card map-transit-card--bus\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Bus</h3>",
      "                        <ul class=\"map-transit-lines\" aria-label=\"Lignes de bus\">",
      "                          <li>39</li>",
      "                          <li>64</li>",
      "                          <li>68</li>",
      "                          <li>111</li>",
      "                          <li>152</li>",
      "                          <li>160</li>",
      "                        </ul>",
      "                      </div>",
      "                    </article>",
      "                  </div>",
      "                </div>",
      "              </div>",
      "            </div>",
      "__GOOGLE_REVIEWS_PLACEHOLDER__",
      "            </div>",
      "          </div>",
      "          <aside id=\"map-review-cta\" class=\"map-review-cta\" aria-label=\"Avis Google\">",
      "            <div class=\"map-review-cta-inner\">",
      "              <span class=\"map-review-cta-icon\" aria-hidden=\"true\"><i class=\"fa fa-star\"></i></span>",
      "              <div class=\"map-review-cta-body\">",
      "                <p class=\"map-review-cta-text\">",
      "                  Vous avez été satisfait(e) de votre visite ?<br>",
      `                  <a href="${googleReviewWriteUrl()}" class="map-review-cta-link" target="_blank" rel="noopener noreferrer" title="Laisser un avis sur Google">Aidez-nous en laissant un avis !</a>`,
      "                </p>",
      "              </div>",
      "            </div>",
      "          </aside>",
      "        </div>",
      "      </div>",
      "      </section>",
      "__FAQ_ACCORDION__",
    ].join("\n"),
  },
  pt: {
    title: "Kinésica — Fisioterapia, osteopatia, RPG e ATM",
    description: "Kinésica é um centro de fisioterapia, osteopatia, RPG e ATM em Palermo com terapias manuais personalizadas.",
    ogDescription: "Kinésica é um centro de fisioterapia, osteopatia, RPG e ATM em Palermo com terapias manuais personalizadas.",
    twitterDescription: "Kinésica é um centro de fisioterapia, osteopatia, RPG e ATM em Palermo com terapias manuais personalizadas.",
    twitterImageAlt: "Clínica Kinésica — fisioterapia, osteopatia, RPG e ATM em Palermo",
    mainHtml: [
      "<section class=\"hero-section\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-5\">",
      "            <h1 class=\"hero-title\">Fisioterapia <br />RPG <br />Osteopatia <br />ATM</h1>",
      "            <p class=\"hero-text\">",
      "              Não se acostume a viver com dor. Juntos, podemos encontrar um caminho para você viver melhor.",
      "            </p>",
      `            <a href="${HOME_WHATSAPP_HREF}" target="_blank" class="btn btn-default dynamic-whatsapp-url"`,
      "              rel=\"noopener noreferrer\">Contato e agendamento</a>",
      "</div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    <section class=\"space-medium section-intro section-intro--band\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-offset-2 col-md-8\">",
      "            <div class=\"mb60 text-center section-title\">",
      "              <!-- section title start-->",
      "              <p class=\"section-eyebrow\">Terapias</p>",
      "              <h2 class=\"heading-line-center\">Métodos e técnicas</h2>",
      "              <p class=\"section-lead\">",
      "                Trabalhamos com <span class=\"text-highlight\">terapia manual</span>.",
      "                Diferentes métodos nos permitem abordar cada paciente de várias",
      "                perspectivas.",
      "              </p>",
      "            </div>",
      "            <!-- /.section title start-->",
      "          </div>",
      "        </div>",
      ...renderHomeMethodCards("pt"),
      "      </div>",
      "    </section>",
      "          __CTA_PLACEHOLDER__",
      ...teamAboutSection("pt"),
      "    <section class=\"space-small bg-default section-intro section-intro--compact\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">",
      "            <div class=\"section-title mb40 text-center\">",
      "              <p class=\"section-eyebrow\">Visite-nos</p>",
      "              <h2 class=\"heading-line-center\">Localização</h2>",
      "            </div>",
      "          </div>",
      "        </div>",
      "        <div class=\"map-block\">",
      "          <div class=\"map-reviews-panel\">",
      "            <div class=\"map-reviews-grid\">",
      "              <div class=\"map-reviews-map\">",
      ...mapEmbedFrameBlock("pt"),
      "                <div class=\"map-transit-wrap\">",
      "                <div class=\"map-transit-panel\">",
      "                  <div class=\"map-transit-grid\">",
      "                    <article class=\"map-transit-card map-transit-card--subte\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-train\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Metrô</h3>",
      "                        <p class=\"map-transit-card-detail\">",
      "                          <span class=\"map-transit-badge map-transit-badge--line-d\">D</span>",
      "                          Scalabrini Ortiz",
      "                        </p>",
      "                      </div>",
      "                    </article>",
      "                    <article class=\"map-transit-card map-transit-card--bus\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Ônibus</h3>",
      "                        <ul class=\"map-transit-lines\" aria-label=\"Linhas de ônibus\">",
      "                          <li>39</li>",
      "                          <li>64</li>",
      "                          <li>68</li>",
      "                          <li>111</li>",
      "                          <li>152</li>",
      "                          <li>160</li>",
      "                        </ul>",
      "                      </div>",
      "                    </article>",
      "                  </div>",
      "                </div>",
      "              </div>",
      "            </div>",
      "__GOOGLE_REVIEWS_PLACEHOLDER__",
      "            </div>",
      "          </div>",
      "          <aside id=\"map-review-cta\" class=\"map-review-cta\" aria-label=\"Avaliações no Google\">",
      "            <div class=\"map-review-cta-inner\">",
      "              <span class=\"map-review-cta-icon\" aria-hidden=\"true\"><i class=\"fa fa-star\"></i></span>",
      "              <div class=\"map-review-cta-body\">",
      "                <p class=\"map-review-cta-text\">",
      "                  Gostou da experiência connosco?<br>",
      `                  <a href="${googleReviewWriteUrl()}" class="map-review-cta-link" target="_blank" rel="noopener noreferrer" title="Deixar uma avaliação no Google">Ajude-nos com uma avaliação!</a>`,
      "                </p>",
      "              </div>",
      "            </div>",
      "          </aside>",
      "        </div>",
      "      </div>",
      "      </section>",
      "__FAQ_ACCORDION__",
    ].join("\n"),
  }
};

/** @typedef {{ title: string, description: string, ogDescription: string, twitterDescription: string, twitterImageAlt: string, mainHtml: string }} HomeLang */

export function homeForLang(lang) {
  return HOME[lang] ?? null;
}

/** Team copy for experimental layouts (index_2). */
export function homeTeamAbout(lang) {
  return TEAM_ABOUT[lang] || TEAM_ABOUT.es;
}

/** Method cards with hrefs for experimental layouts (index_2). */
export function homeMethodCardsForLang(lang) {
  return HOME_METHOD_CARD_STEMS.map((stem) => {
    const card = HOME_METHOD_CARDS[stem][lang];
    return {
      stem,
      href: sitePath(lang, stem),
      image: HOME_METHOD_CARD_IMAGES[stem],
      title: card.title,
      imgTitle: card.imgTitle,
      imgAlt: card.imgAlt,
      lead: card.lead,
    };
  });
}

export { LANG_CODES };
