/**
 * Home page copy and main markup (ES / EN / FR / PT).
 * Edit here, then: npm run build:home
 * Refresh from HTML: node scripts/extract-home-content.mjs
 */
import { LANG_CODES } from "./languages.mjs";
import {
  googleReviewWriteUrl,
  googleReviewsListUrl,
} from "./google-place.mjs";
import { SITE_OG_IMAGE } from "./page-shell.mjs";
import { waMeUrl } from "./site-contact.mjs";

export const HOME_OG_IMAGE = SITE_OG_IMAGE;
/** @deprecated Use HOME_OG_IMAGE for social previews. */
export const HOME_HERO_IMAGE = HOME_OG_IMAGE;

const HOME_WHATSAPP_HREF = waMeUrl();

/** Kinesica + estación Scalabrini Ortiz (D) visibles al cargar. Regenerar: Maps → encuadrar → Compartir → Insertar mapa. */
const MAP_EMBED_BASE =
  "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5720.6828547033!2d-58.421280!3d-34.586220!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcb5d25b8f6967%3A0xb83b91819649edc!2sKinesica!5e0!3m2!1";

/** @param {import("./languages.mjs").LangCode} lang */
export function mapEmbedSrc(lang) {
  const hl = lang === "es" ? "ses" : lang;
  return `${MAP_EMBED_BASE}${hl}!2${hl}!4v1742940067621!5m2!1${hl}!2${hl}`;
}

const MAP_EMBED_TITLES = {
  es: "Ubicación de Kinésica en Google Maps",
  en: "Kinésica location on Google Maps",
  fr: "Localisation de Kinésica sur Google Maps",
  pt: "Localização da Kinésica no Google Maps",
};

/** @param {import("./languages.mjs").LangCode} lang */
export function mapEmbedFrameBlock(lang) {
  const title = MAP_EMBED_TITLES[lang] || MAP_EMBED_TITLES.es;
  const src = mapEmbedSrc(lang);
  return [
    "                <div class=\"map-embed-frame\">",
    `              <div class="map-embed-facade" data-embed-src="${src}" data-embed-title="${title}" aria-label="${title}" aria-busy="true"></div>`,
    "                </div>",
  ];
}

const MAP_REVIEWS_COPY = {
  es: {
    moreReviewsLabel: "Ver todas nuestras valoraciones en Google",
    moreReviewsTitle: "Ver todas nuestras valoraciones en Google",
  },
  en: {
    moreReviewsLabel: "See all our Google reviews",
    moreReviewsTitle: "See all our Google reviews",
  },
  fr: {
    moreReviewsLabel: "Voir toutes nos évaluations sur Google",
    moreReviewsTitle: "Voir toutes nos évaluations sur Google",
  },
  pt: {
    moreReviewsLabel: "Ver todas as nossas avaliações no Google",
    moreReviewsTitle: "Ver todas as nossas avaliações no Google",
  },
};

const TEAM_ABOUT = {
  es: {
    eyebrow: "Profesionales",
    title: "Sobre nosotros",
    lead:
      "Somos kinesiólogos que nos perfeccionamos permanentemente, aprendiendo nuevos métodos para poder ayudarte. Una persona tiene muchos aspectos, y buscamos distintas miradas para comprenderla. Nuestro abordaje es la <span class=\"text-highlight\">Terapia Manual</span>: utilizamos los métodos de tratamiento según la necesidad de cada paciente y la problemática que presente. No te acostumbres a vivir con dolor; podemos encontrar juntos un camino para que vivas mejor. Para ayudarte armamos Kinésica, un centro de atención en kinesiología, osteopatía, RPG y ATM en Palermo.",
    members: [
      {
        name: "Norberto Brude",
        title: "Lic. Kinesiólogo Fisiatra",
        img: "noberto-brude-kinesiologo-osteopata.webp",
        imgTitle: "Norberto Brude Kinesiólogo Osteópata",
        imgAlt: "Norberto Brude Kinesiologo Osteopata",
        cvLabel: "Currículum",
        cvHref: "cv.html",
      },
      {
        name: "María Gulín",
        title: "Lic. Kinesióloga Fisiatra",
        img: "maria.webp",
        imgTitle: "María Gulín Kinesióloga Fisiatra",
        imgAlt: "María Gulín Kinesióloga Fisiatra",
      },
    ],
  },
  en: {
    eyebrow: "Professionals",
    title: "About us",
    lead:
      "We are kinesiologists who continuously refine our skills by learning new methods to better assist you. A person has many aspects, and we seek different perspectives to understand them. Our approach is <span class=\"text-highlight\">Manual Therapy</span>: we apply treatment methods according to each patient's needs and specific condition. Don't get used to living with pain; together we can find a path for you to live better. To help you, we created Kinésica, a clinic for kinesiology, osteopathy, RPG, and TMJ in Palermo.",
    members: [
      {
        name: "Norberto Brude",
        title: "Licensed Kinesiologist & Physiatrist",
        img: "noberto-brude-kinesiologo-osteopata.webp",
        imgTitle: "Norberto Brude Physiotherapist Osteopath",
        imgAlt: "Norberto Brude Physiotherapist Osteopath",
        cvLabel: "Résumé",
        cvHref: "cv.html",
      },
      {
        name: "María Gulín",
        title: "Licensed Kinesiologist & Physiatrist",
        img: "maria.webp",
        imgTitle: "María Gulín Licensed Kinesiologist & Physiatrist",
        imgAlt: "María Gulín Licensed Kinesiologist & Physiatrist",
      },
    ],
  },
  fr: {
    eyebrow: "Praticiens",
    title: "À propos de nous",
    lead:
      "Nous sommes kinésithérapeutes et affinons continuellement nos compétences pour mieux vous accompagner. Une personne a de nombreuses dimensions : nous cherchons plusieurs perspectives pour les comprendre. Notre approche est la <span class=\"text-highlight\">thérapie manuelle</span> : nous adaptons les techniques aux besoins et à l'état de chaque patient. N'habituez pas votre corps à la douleur ; ensemble, nous pouvons trouver un chemin vers un mieux-être. Pour vous aider, nous avons créé Kinésica, un cabinet de kinésithérapie, ostéopathie, RPG et ATM à Palermo.",
    members: [
      {
        name: "Norberto Brude",
        title: "Kinésithérapeute et physiatre",
        img: "noberto-brude-kinesiologo-osteopata.webp",
        imgTitle: "Norberto Brude — kinésithérapeute ostéopathe",
        imgAlt: "Norberto Brude — kinésithérapeute ostéopathe",
        cvLabel: "CV",
        cvHref: "cv.html",
      },
      {
        name: "María Gulín",
        title: "Kinésithérapeute et physiatre",
        img: "maria.webp",
        imgTitle: "María Gulín — kinésithérapeute et physiatre",
        imgAlt: "María Gulín — kinésithérapeute et physiatre",
      },
    ],
  },
  pt: {
    eyebrow: "Profissionais",
    title: "Sobre nós",
    lead:
      "Somos fisioterapeutas e aprimoramos continuamente nossas habilidades, incorporando novos métodos para cuidar melhor de você. Uma pessoa tem muitos aspectos, e buscamos diferentes perspectivas para compreendê-la. Nossa abordagem é a <span class=\"text-highlight\">terapia manual</span>: aplicamos cada técnica conforme a necessidade e a condição de cada paciente. Não se acostume a viver com dor; podemos encontrar juntos um caminho para você viver melhor. Para ajudá-lo, criamos a Kinésica, um centro de fisioterapia, osteopatia, RPG e ATM em Palermo.",
    members: [
      {
        name: "Norberto Brude",
        title: "Licenciado em fisioterapia e fisiatria",
        img: "noberto-brude-kinesiologo-osteopata.webp",
        imgTitle: "Norberto Brude — fisioterapeuta e osteopata",
        imgAlt: "Norberto Brude — fisioterapeuta e osteopata",
        cvLabel: "Currículo",
        cvHref: "cv.html",
      },
      {
        name: "María Gulín",
        title: "Licenciada em fisioterapia e fisiatria",
        img: "maria.webp",
        imgTitle: "María Gulín — fisioterapeuta e fisiatra",
        imgAlt: "María Gulín — fisioterapeuta e fisiatra",
      },
    ],
  },
};

/** @param {import("./languages.mjs").LangCode} lang */
function teamAboutSection(lang) {
  const copy = TEAM_ABOUT[lang] || TEAM_ABOUT.es;
  const memberBlocks = copy.members.flatMap((member) => {
    const cvMeta = member.cvHref
      ? [
          "                <div class=\"team-meta\">",
          "                  <span class=\"team-designation\">",
          `                    <a href=\"${member.cvHref}\">${member.cvLabel}</a>`,
          "                  </span>",
          "                </div>",
        ]
      : [];
    return [
      "              <div class=\"team-block\">",
      "                <div class=\"team-img\">",
      `                  <img src=\"__PREFIX__images/${member.img}\" title=\"${member.imgTitle}\"`,
      `                    alt=\"${member.imgAlt}\" class=\"team-photo center-block d-block\" width=\"314\"`,
      "                    height=\"372\" loading=\"lazy\" />",
      "                </div>",
      "                <div class=\"team-content\">",
      `                  <h2 class=\"team-title\">${member.name}</h2>`,
      "                  <div class=\"team-meta\">",
      `                    <span class=\"team-designation\">${member.title}</span>`,
      "                  </div>",
      ...cvMeta,
      "                </div>",
      "              </div>",
    ];
  });

  return [
    "<section class=\"space-medium section-intro section-intro--about\">",
    "      <div class=\"container\">",
    "        <div class=\"row\">",
    "          <div class=\"col-lg-offset-1 col-lg-10 col-md-offset-1 col-md-10 col-sm-12 col-xs-12\">",
    "            <div class=\"section-title mb60 text-center\">",
    "              <!-- section title start-->",
    `              <p class=\"section-eyebrow\">${copy.eyebrow}</p>`,
    `              <h2 class=\"heading-line-center\">${copy.title}</h2>`,
    "              <p class=\"section-lead\">",
    `                ${copy.lead}`,
    "              </p>",
    "            </div>",
    "            <!-- /.section title end-->",
    "          </div>",
    "        </div>",
    "        <div class=\"row\">",
    "          <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">",
    "            <div class=\"team-grid\">",
    ...memberBlocks,
    "            </div>",
    "          </div>",
    "        </div>",
    "      </div>",
    "    </section>",
  ];
}

/** Google review cards (Places API → npm run reviews:fetch or js/google-reviews.js). */
export function googleReviewsBlock(lang) {
  const copy = MAP_REVIEWS_COPY[lang] || MAP_REVIEWS_COPY.es;
  const listUrl = googleReviewsListUrl();
  return [
    "            <div class=\"map-reviews-aside\" hidden>",
    "              <div class=\"google-reviews-wrap\">",
    `              <section id="google-reviews-section" class="google-reviews" data-reviews-lang="${lang}" hidden>`,
    "                <div id=\"google-reviews-grid\" class=\"google-reviews-grid\"></div>",
    "              </section>",
    "              <script src=\"__PREFIX__js/reviews.min.js\" defer></script>",
    "              </div>",
    "              <p class=\"google-reviews-more\">",
    `                <a href="${listUrl}" class="google-reviews-more-link" target="_blank" rel="noopener noreferrer" title="${copy.moreReviewsTitle}">${copy.moreReviewsLabel} <i class="fa fa-arrow-right" aria-hidden="true"></i></a>`,
    "              </p>",
    "            </div>",
  ];
}

/** @type {Record<import("./languages.mjs").LangCode, HomeLang>} */
export const HOME = {
  es: {
    title: "Kinésica - Kinesiología, Osteopatía, RPG y ATM",
    description: "Kinésica es un centro de kinesiología, osteopatía, RPG y ATM en Palermo. Terapias manuales personalizadas.",
    ogDescription: "Kinésica es un centro de kinesiología, osteopatía, RPG y ATM en Palermo. Terapias manuales personalizadas.",
    twitterDescription: "Kinésica es un centro de kinesiología, osteopatía, RPG y ATM en Palermo. Terapias manuales personalizadas.",
    twitterImageAlt: "Centro Kinésica — kinesiología, osteopatía, RPG y ATM en Palermo",
    mainHtml: [
      "<section class=\"hero-section\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-5\">",
      "            <h1 class=\"hero-title\">Kinesiología <br />RPG <br />Osteopatía <br />ATM</h1>",
      "            <p class=\"hero-text\">",
      "              No te acostumbres a vivir con dolor, podemos encontrar juntos un",
      "              camino para que vivas mejor.",
      "            </p>",
      `            <a href="${HOME_WHATSAPP_HREF}" target="_blank" class="btn btn-default dynamic-whatsapp-url"`,
      "              rel=\"noopener noreferrer\">Contacto y turnos</a>",
      "</div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    <section class=\"space-medium section-intro section-intro--band\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-offset-2 col-md-8\">",
      "            <div class=\"mb60 text-center section-title\">",
      "              <!-- section title start-->",
      "              <p class=\"section-eyebrow\">Terapias</p>",
      "              <h2 class=\"heading-line-center\">Métodos y Técnicas</h2>",
      "              <p class=\"section-lead\">",
      "                Trabajamos en <span class=\"text-highlight\">Terapia Manual</span>.",
      "                Los diferentes métodos nos permiten abordar al paciente desde",
      "                distintos puntos de vista.",
      "              </p>",
      "            </div>",
      "            <!-- /.section title start-->",
      "          </div>",
      "        </div>",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"rpg.html\"><img src=\"__PREFIX__images/rpg.webp\" title=\"rpg\"",
      "                    alt=\"Sesión de Reeducación Postural Global (RPG)\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2><a href=\"rpg.html\" class=\"title\">RPG</a></h2>",
      "                <p>",
      "                  Trabaja sobre la flexibilización de los músculos estáticos.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"osteopatia.html\"><img src=\"__PREFIX__images/osteopatia.webp\" title=\"osteopatía\"",
      "                    alt=\"Tratamiento de Osteopatía manual\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2><a href=\"osteopatia.html\" class=\"title\">Osteopatía</a></h2>",
      "                <p>",
      "                  Busca la movilidad de los tejidos para restablecer la salud.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"cadenas.html\"><img src=\"__PREFIX__images/cadenas_fisiologicas.webp\" title=\"Cadenas Fisiológicas\"",
      "                    alt=\"Tratamiento de Cadenas Fisiológicas\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"cadenas.html\" class=\"title\">Cadenas Fisiológicas</a>",
      "                </h2>",
      "                <p>",
      "                  Define la relación entre la estructura corporal y el contenido",
      "                  visceral para comprender cómo funcionamos en la estática y el",
      "                  movimiento",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          ",
      "        </div>",
      "        <br />",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"manipulaciones.html\"><img src=\"__PREFIX__images/manipulaciones_viscerales.webp\"",
      "                    title=\"Manipulaciones Viscerales\" alt=\"Terapia de manipulaciones viscerales\" class=\"img-responsive\"",
      "                    loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"manipulaciones.html\" class=\"title\">Manipulaciones viscerales</a>",
      "                </h2>",
      "                <p>",
      "                  Las tensiones viscerales se transmiten al aparato locomotor",
      "                  condicionando su función.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"neurodinamia.html\"><img src=\"__PREFIX__images/neurodinamia.webp\" title=\"Neurodinamia\"",
      "                    alt=\"Tratamiento de Neurodinamia\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"neurodinamia.html\" class=\"title\">Neurodinamia</a>",
      "                </h2>",
      "                <p>",
      "                  Estudia y trata los trastornos del sistema nervioso,",
      "                  enfocándose en cómo los nervios se deslizan y responden al",
      "                  estrés físico, buscando aliviar el dolor y mejorar la función",
      "                  neurológica.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <div class=\"service-img mb20\">",
      "                <a href=\"atm.html\"><img src=\"__PREFIX__images/atm.webp\" title=\"ATM\"",
      "                    alt=\"Tratamiento de ATM – articulación temporomandibular\" class=\"img-responsive\"",
      "                    loading=\"lazy\" /></a>",
      "              </div>",
      "              <div class=\"service-content\">",
      "                <h2><a href=\"atm.html\" class=\"title\">ATM</a></h2>",
      "                <p>",
      "                  ATM (Articulación Temporomandibular) es una especialidad que trata las disfunciones de la",
      "                  mandíbula, aliviando dolor, chasquidos y bruxismo mediante terapia manual, ejercicios y",
      "                  reeducación postural.",
      "                </p>",
      "              </div>",
      "            </div>",
      "          </div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    __CTA_PLACEHOLDER__",
      ...teamAboutSection("es"),
      "    <section class=\"space-small bg-default section-intro section-intro--compact\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">",
      "            <div class=\"section-title mb40 text-center\">",
      "              <p class=\"section-eyebrow\">Ubicación</p>",
      "              <h2 class=\"heading-line-center\">¿Dónde estamos?</h2>",
      "            </div>",
      "          </div>",
      "        </div>",
      "        <div class=\"map-block\">",
      "          <div class=\"map-reviews-panel\">",
      "            <div class=\"map-reviews-grid\">",
      "              <div class=\"map-reviews-map\">",
      ...mapEmbedFrameBlock("es"),
      "                <div class=\"map-transit-wrap\">",
      "                <div class=\"map-transit-panel\">",
      "                  <div class=\"map-transit-grid\">",
      "                    <article class=\"map-transit-card map-transit-card--subte\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-train\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Subte</h3>",
      "                        <p class=\"map-transit-card-detail\">",
      "                          <span class=\"map-transit-badge map-transit-badge--line-d\">D</span>",
      "                          Scalabrini Ortiz",
      "                        </p>",
      "                      </div>",
      "                    </article>",
      "                    <article class=\"map-transit-card map-transit-card--bus\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Colectivos</h3>",
      "                        <ul class=\"map-transit-lines\" aria-label=\"Líneas de colectivo\">",
      "                          <li>39</li>",
      "                          <li>64</li>",
      "                          <li>68</li>",
      "                          <li>111</li>",
      "                          <li>152</li>",
      "                          <li>160</li>",
      "                        </ul>",
      "                      </div>",
      "                    </article>",
      "                  </div>",
      "                </div>",
      "              </div>",
      "            </div>",
      "__GOOGLE_REVIEWS_PLACEHOLDER__",
      "            </div>",
      "          </div>",
      "          <aside id=\"map-review-cta\" class=\"map-review-cta\" aria-label=\"Reseñas en Google\">",
      "            <div class=\"map-review-cta-inner\">",
      "              <span class=\"map-review-cta-icon\" aria-hidden=\"true\"><i class=\"fa fa-star\"></i></span>",
      "              <div class=\"map-review-cta-body\">",
      "                <p class=\"map-review-cta-text\">",
      "                  ¿Te ha ido bien con nosotros?<br>",
      `                  <a href="${googleReviewWriteUrl()}" class="map-review-cta-link" target="_blank" rel="noopener noreferrer" title="Dejar una reseña en Google">¡Ayúdanos con una reseña!</a>`,
      "                </p>",
      "              </div>",
      "            </div>",
      "          </aside>",
      "        </div>",
      "      </div>",
      "    </section>",
      "__FAQ_ACCORDION__",
    ].join("\n"),
  },
  en: {
    title: "Kinésica - Kinesiology, Osteopathy, RPG and TMJ",
    description: "Kinésica is a clinic for kinesiology, osteopathy, RPG, and TMJ in Palermo offering personalized manual therapy.",
    ogDescription: "Kinésica is a clinic for kinesiology, osteopathy, RPG, and TMJ in Palermo offering personalized manual therapy.",
    twitterDescription: "Kinésica is a clinic for kinesiology, osteopathy, RPG, and TMJ in Palermo offering personalized manual therapy.",
    twitterImageAlt: "Kinésica clinic — kinesiology, osteopathy, RPG and TMJ in Palermo",
    mainHtml: [
      "<section class=\"hero-section\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-5\">",
      "            <h1 class=\"hero-title\">Kinesiology <br />RPG <br />Osteopathy <br />TMJ</h1>",
      "            <p class=\"hero-text\">",
      "              Don't get used to living in pain. Together, we can find a way for",
      "              you to live better.",
      "            </p>",
      `            <a href="${HOME_WHATSAPP_HREF}" target="_blank" class="btn btn-default dynamic-whatsapp-url"`,
      "              rel=\"noopener noreferrer\">Contact & Appointments</a>",
      "</div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    <section class=\"space-medium section-intro section-intro--band\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-offset-2 col-md-8\">",
      "            <div class=\"mb60 text-center section-title\">",
      "              <!-- section title start-->",
      "              <p class=\"section-eyebrow\">Therapies</p>",
      "              <h2 class=\"heading-line-center\">Methods &amp; Techniques</h2>",
      "              <p class=\"section-lead\">",
      "                We work with <span class=\"text-highlight\">Manual Therapy</span>.",
      "                Different methods allow us to approach patients from various",
      "                perspectives.",
      "              </p>",
      "            </div>",
      "            <!-- /.section title start-->",
      "          </div>",
      "        </div>",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"rpg.html\"><img src=\"__PREFIX__images/rpg.webp\" title=\"RPG\"",
      "                    alt=\"Global Postural Reeducation (RPG) session\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2><a href=\"rpg.html\" class=\"title\">RPG</a></h2>",
      "                <p>Focuses on the flexibility of static muscles.</p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"osteopatia.html\"><img src=\"__PREFIX__images/osteopatia.webp\" title=\"Osteopathy\"",
      "                    alt=\"Manual Osteopathy treatment\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"osteopatia.html\" class=\"title\">Osteopathy</a>",
      "                </h2>",
      "                <p>Aims to restore health by improving tissue mobility.</p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"cadenas.html\"><img src=\"__PREFIX__images/cadenas_fisiologicas.webp\" title=\"Physiological Chains\"",
      "                    alt=\"Physiological Chains treatment\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"cadenas.html\" class=\"title\">Physiological Chains</a>",
      "                </h2>",
      "                <p>",
      "                  Defines the relationship between body structure and visceral",
      "                  content to understand how we function in both static and",
      "                  movement.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "        </div>",
      "        <br />",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"manipulaciones.html\"><img src=\"__PREFIX__images/manipulaciones_viscerales.webp\"",
      "                    title=\"Visceral manipulations\" alt=\"Visceral manipulations therapy\" class=\"img-responsive\"",
      "                    loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"manipulaciones.html\" class=\"title\">Visceral Manipulations</a>",
      "                </h2>",
      "                <p>",
      "                  Visceral tensions are transmitted to the locomotor system,",
      "                  affecting its function.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"neurodinamia.html\"><img src=\"__PREFIX__images/neurodinamia.webp\" title=\"Neurodynamics\"",
      "                    alt=\"Neurodynamics treatment\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"neurodinamia.html\" class=\"title\">Neurodynamics</a>",
      "                </h2>",
      "                <p>",
      "                  Studies and treats nervous system disorders, focusing on how",
      "                  nerves glide and respond to physical stress, aiming to relieve",
      "                  pain and improve neurological function.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <div class=\"service-img mb20\">",
      "                <a href=\"atm.html\"><img src=\"__PREFIX__images/atm.webp\" title=\"TMJ\"",
      "                    alt=\"TMJ temporomandibular joint treatment\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <div class=\"service-content\">",
      "                <h2><a href=\"atm.html\" class=\"title\">TMJ</a></h2>",
      "                <p>",
      "                  TMJ (Temporomandibular Joint) is a specialty that treats jaw dysfunctions, relieving pain,",
      "                  clicking and bruxism through manual therapy, exercises and postural re-education.",
      "                </p>",
      "              </div>",
      "            </div>",
      "          </div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "          __CTA_PLACEHOLDER__",
      ...teamAboutSection("en"),
      "    <section class=\"space-small bg-default section-intro section-intro--compact\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">",
      "            <div class=\"section-title mb40 text-center\">",
      "              <p class=\"section-eyebrow\">Visit us</p>",
      "              <h2 class=\"heading-line-center\">Location</h2>",
      "            </div>",
      "          </div>",
      "        </div>",
      "        <div class=\"map-block\">",
      "          <div class=\"map-reviews-panel\">",
      "            <div class=\"map-reviews-grid\">",
      "              <div class=\"map-reviews-map\">",
      ...mapEmbedFrameBlock("en"),
      "                <div class=\"map-transit-wrap\">",
      "                <div class=\"map-transit-panel\">",
      "                  <div class=\"map-transit-grid\">",
      "                    <article class=\"map-transit-card map-transit-card--subte\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-train\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Subway</h3>",
      "                        <p class=\"map-transit-card-detail\">",
      "                          <span class=\"map-transit-badge map-transit-badge--line-d\">D</span>",
      "                          Scalabrini Ortiz",
      "                        </p>",
      "                      </div>",
      "                    </article>",
      "                    <article class=\"map-transit-card map-transit-card--bus\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Buses</h3>",
      "                        <ul class=\"map-transit-lines\" aria-label=\"Bus routes\">",
      "                          <li>39</li>",
      "                          <li>64</li>",
      "                          <li>68</li>",
      "                          <li>111</li>",
      "                          <li>152</li>",
      "                          <li>160</li>",
      "                        </ul>",
      "                      </div>",
      "                    </article>",
      "                  </div>",
      "                </div>",
      "              </div>",
      "            </div>",
      "__GOOGLE_REVIEWS_PLACEHOLDER__",
      "            </div>",
      "          </div>",
      "          <aside id=\"map-review-cta\" class=\"map-review-cta\" aria-label=\"Google reviews\">",
      "            <div class=\"map-review-cta-inner\">",
      "              <span class=\"map-review-cta-icon\" aria-hidden=\"true\"><i class=\"fa fa-star\"></i></span>",
      "              <div class=\"map-review-cta-body\">",
      "                <p class=\"map-review-cta-text\">",
      "                  Had a good experience with us?<br>",
      `                  <a href="${googleReviewWriteUrl()}" class="map-review-cta-link" target="_blank" rel="noopener noreferrer" title="Leave a review on Google">Help us with a review!</a>`,
      "                </p>",
      "              </div>",
      "            </div>",
      "          </aside>",
      "        </div>",
      "      </div>",
      "      </section>",
      "__FAQ_ACCORDION__",
    ].join("\n"),
  },
  fr: {
    title: "Kinésica — Kinésithérapie, ostéopathie, RPG et ATM",
    description: "Kinésica est un centre de kinésithérapie, ostéopathie, RPG et ATM à Palermo. Thérapies manuelles personnalisées.",
    ogDescription: "Kinésica est un centre de kinésithérapie, ostéopathie, RPG et ATM à Palermo. Thérapies manuelles personnalisées.",
    twitterDescription: "Kinésica est un centre de kinésithérapie, ostéopathie, RPG et ATM à Palermo. Thérapies manuelles personnalisées.",
    twitterImageAlt: "Centre Kinésica — kinésithérapie, ostéopathie, RPG et ATM à Palermo",
    mainHtml: [
      "<section class=\"hero-section\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-5\">",
      "            <h1 class=\"hero-title\">Kinésithérapie <br />RPG <br />Ostéopathie <br />ATM</h1>",
      "            <p class=\"hero-text\">",
      "              N'habituez pas votre corps à la douleur. Ensemble, nous pouvons trouver une façon de mieux vivre.",
      "            </p>",
      `            <a href="${HOME_WHATSAPP_HREF}" target="_blank" class="btn btn-default dynamic-whatsapp-url"`,
      "              rel=\"noopener noreferrer\">Contact et rendez-vous</a>",
      "</div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    <section class=\"space-medium section-intro section-intro--band\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-offset-2 col-md-8\">",
      "            <div class=\"mb60 text-center section-title\">",
      "              <!-- section title start-->",
      "              <p class=\"section-eyebrow\">Thérapies</p>",
      "              <h2 class=\"heading-line-center\">Méthodes et techniques</h2>",
      "              <p class=\"section-lead\">",
      "                Nous pratiquons la <span class=\"text-highlight\">thérapie manuelle</span>.",
      "                Différentes méthodes nous permettent d'aborder chaque patient sous",
      "                plusieurs angles.",
      "              </p>",
      "            </div>",
      "            <!-- /.section title start-->",
      "          </div>",
      "        </div>",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"rpg.html\"><img src=\"__PREFIX__images/rpg.webp\" title=\"RPG\"",
      "                    alt=\"Séance de rééducation posturale globale (RPG)\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2><a href=\"rpg.html\" class=\"title\">RPG</a></h2>",
      "                <p>Axé sur la souplesse des muscles statiques.</p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"osteopatia.html\"><img src=\"__PREFIX__images/osteopatia.webp\" title=\"Ostéopathie\"",
      "                    alt=\"Traitement d'ostéopathie manuelle\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"osteopatia.html\" class=\"title\">Ostéopathie</a>",
      "                </h2>",
      "                <p>Vise à restaurer la santé en améliorant la mobilité des tissus.</p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"cadenas.html\"><img src=\"__PREFIX__images/cadenas_fisiologicas.webp\" title=\"Chaînes physiologiques\"",
      "                    alt=\"Traitement des chaînes physiologiques\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"cadenas.html\" class=\"title\">Chaînes physiologiques</a>",
      "                </h2>",
      "                <p>",
      "                  Définit la relation entre la structure corporelle et les fonctions viscérales pour comprendre notre fonctionnement au repos et en mouvement.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "        </div>",
      "        <br />",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"manipulaciones.html\"><img src=\"__PREFIX__images/manipulaciones_viscerales.webp\"",
      "                    title=\"Manipulations viscérales\" alt=\"Thérapie par manipulations viscérales\" class=\"img-responsive\"",
      "                    loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"manipulaciones.html\" class=\"title\">Manipulations viscérales</a>",
      "                </h2>",
      "                <p>",
      "                  Les tensions viscérales se transmettent à l'appareil locomoteur et affectent sa fonction.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"neurodinamia.html\"><img src=\"__PREFIX__images/neurodinamia.webp\" title=\"Neurodynamique\"",
      "                    alt=\"Traitement neurodynamique\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"neurodinamia.html\" class=\"title\">Neurodynamique</a>",
      "                </h2>",
      "                <p>",
      "                  Étudie et traite les troubles nerveux, en particulier la glisse des nerfs et leur réponse au stress physique, pour soulager la douleur et améliorer la fonction neurologique.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <div class=\"service-img mb20\">",
      "                <a href=\"atm.html\"><img src=\"__PREFIX__images/atm.webp\" title=\"ATM\"",
      "                    alt=\"Traitement de l'ATM (articulation temporomandibulaire)\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <div class=\"service-content\">",
      "                <h2><a href=\"atm.html\" class=\"title\">ATM</a></h2>",
      "                <p>",
      "                  L'ATM (articulation temporomandibulaire) est une spécialité qui traite les dysfonctions de la mâchoire : douleur, claquements et bruxisme, par thérapie manuelle, exercices et rééducation posturale.",
      "                </p>",
      "              </div>",
      "            </div>",
      "          </div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "          __CTA_PLACEHOLDER__",
      ...teamAboutSection("fr"),
      "    <section class=\"space-small bg-default section-intro section-intro--compact\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">",
      "            <div class=\"section-title mb40 text-center\">",
      "              <p class=\"section-eyebrow\">Adresse</p>",
      "              <h2 class=\"heading-line-center\">Localisation</h2>",
      "            </div>",
      "          </div>",
      "        </div>",
      "        <div class=\"map-block\">",
      "          <div class=\"map-reviews-panel\">",
      "            <div class=\"map-reviews-grid\">",
      "              <div class=\"map-reviews-map\">",
      ...mapEmbedFrameBlock("fr"),
      "                <div class=\"map-transit-wrap\">",
      "                <div class=\"map-transit-panel\">",
      "                  <div class=\"map-transit-grid\">",
      "                    <article class=\"map-transit-card map-transit-card--subte\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-train\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Métro</h3>",
      "                        <p class=\"map-transit-card-detail\">",
      "                          <span class=\"map-transit-badge map-transit-badge--line-d\">D</span>",
      "                          Scalabrini Ortiz",
      "                        </p>",
      "                      </div>",
      "                    </article>",
      "                    <article class=\"map-transit-card map-transit-card--bus\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Bus</h3>",
      "                        <ul class=\"map-transit-lines\" aria-label=\"Lignes de bus\">",
      "                          <li>39</li>",
      "                          <li>64</li>",
      "                          <li>68</li>",
      "                          <li>111</li>",
      "                          <li>152</li>",
      "                          <li>160</li>",
      "                        </ul>",
      "                      </div>",
      "                    </article>",
      "                  </div>",
      "                </div>",
      "              </div>",
      "            </div>",
      "__GOOGLE_REVIEWS_PLACEHOLDER__",
      "            </div>",
      "          </div>",
      "          <aside id=\"map-review-cta\" class=\"map-review-cta\" aria-label=\"Avis Google\">",
      "            <div class=\"map-review-cta-inner\">",
      "              <span class=\"map-review-cta-icon\" aria-hidden=\"true\"><i class=\"fa fa-star\"></i></span>",
      "              <div class=\"map-review-cta-body\">",
      "                <p class=\"map-review-cta-text\">",
      "                  Vous avez été satisfait(e) de votre visite ?<br>",
      `                  <a href="${googleReviewWriteUrl()}" class="map-review-cta-link" target="_blank" rel="noopener noreferrer" title="Laisser un avis sur Google">Aidez-nous en laissant un avis !</a>`,
      "                </p>",
      "              </div>",
      "            </div>",
      "          </aside>",
      "        </div>",
      "      </div>",
      "      </section>",
      "__FAQ_ACCORDION__",
    ].join("\n"),
  },
  pt: {
    title: "Kinésica — Fisioterapia, osteopatia, RPG e ATM",
    description: "Kinésica é um centro de fisioterapia, osteopatia, RPG e ATM em Palermo com terapias manuais personalizadas.",
    ogDescription: "Kinésica é um centro de fisioterapia, osteopatia, RPG e ATM em Palermo com terapias manuais personalizadas.",
    twitterDescription: "Kinésica é um centro de fisioterapia, osteopatia, RPG e ATM em Palermo com terapias manuais personalizadas.",
    twitterImageAlt: "Clínica Kinésica — fisioterapia, osteopatia, RPG e ATM em Palermo",
    mainHtml: [
      "<section class=\"hero-section\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-5\">",
      "            <h1 class=\"hero-title\">Fisioterapia <br />RPG <br />Osteopatia <br />ATM</h1>",
      "            <p class=\"hero-text\">",
      "              Não se acostume a viver com dor. Juntos, podemos encontrar um caminho para você viver melhor.",
      "            </p>",
      `            <a href="${HOME_WHATSAPP_HREF}" target="_blank" class="btn btn-default dynamic-whatsapp-url"`,
      "              rel=\"noopener noreferrer\">Contato e agendamento</a>",
      "</div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "    <section class=\"space-medium section-intro section-intro--band\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-md-offset-2 col-md-8\">",
      "            <div class=\"mb60 text-center section-title\">",
      "              <!-- section title start-->",
      "              <p class=\"section-eyebrow\">Terapias</p>",
      "              <h2 class=\"heading-line-center\">Métodos e técnicas</h2>",
      "              <p class=\"section-lead\">",
      "                Trabalhamos com <span class=\"text-highlight\">terapia manual</span>.",
      "                Diferentes métodos nos permitem abordar cada paciente de várias",
      "                perspectivas.",
      "              </p>",
      "            </div>",
      "            <!-- /.section title start-->",
      "          </div>",
      "        </div>",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"rpg.html\"><img src=\"__PREFIX__images/rpg.webp\" title=\"RPG\"",
      "                    alt=\"Sessão de Reeducação Postural Global (RPG)\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2><a href=\"rpg.html\" class=\"title\">RPG</a></h2>",
      "                <p>Foca na flexibilidade dos músculos estáticos.</p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"osteopatia.html\"><img src=\"__PREFIX__images/osteopatia.webp\" title=\"Osteopatia\"",
      "                    alt=\"Tratamento de osteopatia manual\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"osteopatia.html\" class=\"title\">Osteopatia</a>",
      "                </h2>",
      "                <p>Busca restaurar a saúde melhorando a mobilidade dos tecidos.</p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"cadenas.html\"><img src=\"__PREFIX__images/cadenas_fisiologicas.webp\" title=\"Cadeias fisiológicas\"",
      "                    alt=\"Tratamento de cadeias fisiológicas\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"cadenas.html\" class=\"title\">Cadeias fisiológicas</a>",
      "                </h2>",
      "                <p>",
      "                  Define a relação entre a estrutura corporal e as funções viscerais para entender como funcionamos no repouso e no movimento.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "        </div>",
      "        <br />",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"manipulaciones.html\"><img src=\"__PREFIX__images/manipulaciones_viscerales.webp\"",
      "                    title=\"Manipulações viscerais\" alt=\"Terapia por manipulações viscerais\" class=\"img-responsive\"",
      "                    loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"manipulaciones.html\" class=\"title\">Manipulações viscerais</a>",
      "                </h2>",
      "                <p>",
      "                  Tensões viscerais se transmitem ao sistema locomotor e afetam sua função.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <!-- service block -->",
      "              <div class=\"service-img mb20\">",
      "                <!-- service img -->",
      "                <a href=\"neurodinamia.html\"><img src=\"__PREFIX__images/neurodinamia.webp\" title=\"Neurodinâmica\"",
      "                    alt=\"Tratamento de neurodinâmica\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <!-- service img -->",
      "              <div class=\"service-content\">",
      "                <!-- service content -->",
      "                <h2>",
      "                  <a href=\"neurodinamia.html\" class=\"title\">Neurodinâmica</a>",
      "                </h2>",
      "                <p>",
      "                  Estuda e trata distúrbios do sistema nervoso, focando em como os nervos deslizam e respondem ao estresse físico, aliviando dor e melhorando a função neurológica.",
      "                </p>",
      "              </div>",
      "              <!-- service content -->",
      "            </div>",
      "            <!-- /.service block -->",
      "          </div>",
      "          <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">",
      "            <div class=\"service-block\">",
      "              <div class=\"service-img mb20\">",
      "                <a href=\"atm.html\"><img src=\"__PREFIX__images/atm.webp\" title=\"ATM\"",
      "                    alt=\"Tratamento de ATM (articulação temporomandibular)\" class=\"img-responsive\" loading=\"lazy\" /></a>",
      "              </div>",
      "              <div class=\"service-content\">",
      "                <h2><a href=\"atm.html\" class=\"title\">ATM</a></h2>",
      "                <p>",
      "                  A ATM (articulação temporomandibular) trata disfunções da mandíbula, aliviando dor, estalos e bruxismo com terapia manual, exercícios e reeducação postural.",
      "                </p>",
      "              </div>",
      "            </div>",
      "          </div>",
      "        </div>",
      "      </div>",
      "    </section>",
      "          __CTA_PLACEHOLDER__",
      ...teamAboutSection("pt"),
      "    <section class=\"space-small bg-default section-intro section-intro--compact\">",
      "      <div class=\"container\">",
      "        <div class=\"row\">",
      "          <div class=\"col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-12 col-xs-12\">",
      "            <div class=\"section-title mb40 text-center\">",
      "              <p class=\"section-eyebrow\">Visite-nos</p>",
      "              <h2 class=\"heading-line-center\">Localização</h2>",
      "            </div>",
      "          </div>",
      "        </div>",
      "        <div class=\"map-block\">",
      "          <div class=\"map-reviews-panel\">",
      "            <div class=\"map-reviews-grid\">",
      "              <div class=\"map-reviews-map\">",
      ...mapEmbedFrameBlock("pt"),
      "                <div class=\"map-transit-wrap\">",
      "                <div class=\"map-transit-panel\">",
      "                  <div class=\"map-transit-grid\">",
      "                    <article class=\"map-transit-card map-transit-card--subte\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-train\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Metrô</h3>",
      "                        <p class=\"map-transit-card-detail\">",
      "                          <span class=\"map-transit-badge map-transit-badge--line-d\">D</span>",
      "                          Scalabrini Ortiz",
      "                        </p>",
      "                      </div>",
      "                    </article>",
      "                    <article class=\"map-transit-card map-transit-card--bus\">",
      "                      <div class=\"map-transit-card-icon\" aria-hidden=\"true\">",
      "                        <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>",
      "                      </div>",
      "                      <div class=\"map-transit-card-body\">",
      "                        <h3 class=\"map-transit-card-title\">Ônibus</h3>",
      "                        <ul class=\"map-transit-lines\" aria-label=\"Linhas de ônibus\">",
      "                          <li>39</li>",
      "                          <li>64</li>",
      "                          <li>68</li>",
      "                          <li>111</li>",
      "                          <li>152</li>",
      "                          <li>160</li>",
      "                        </ul>",
      "                      </div>",
      "                    </article>",
      "                  </div>",
      "                </div>",
      "              </div>",
      "            </div>",
      "__GOOGLE_REVIEWS_PLACEHOLDER__",
      "            </div>",
      "          </div>",
      "          <aside id=\"map-review-cta\" class=\"map-review-cta\" aria-label=\"Avaliações no Google\">",
      "            <div class=\"map-review-cta-inner\">",
      "              <span class=\"map-review-cta-icon\" aria-hidden=\"true\"><i class=\"fa fa-star\"></i></span>",
      "              <div class=\"map-review-cta-body\">",
      "                <p class=\"map-review-cta-text\">",
      "                  Gostou da experiência connosco?<br>",
      `                  <a href="${googleReviewWriteUrl()}" class="map-review-cta-link" target="_blank" rel="noopener noreferrer" title="Deixar uma avaliação no Google">Ajude-nos com uma avaliação!</a>`,
      "                </p>",
      "              </div>",
      "            </div>",
      "          </aside>",
      "        </div>",
      "      </div>",
      "      </section>",
      "__FAQ_ACCORDION__",
    ].join("\n"),
  }
};

/** @typedef {{ title: string, description: string, ogDescription: string, twitterDescription: string, twitterImageAlt: string, mainHtml: string }} HomeLang */

export function homeForLang(lang) {
  return HOME[lang] ?? null;
}

export { LANG_CODES };
